
ALTER TABLE public.characters
  ADD COLUMN IF NOT EXISTS class text,
  ADD COLUMN IF NOT EXISTS subclass text,
  ADD COLUMN IF NOT EXISTS race text,
  ADD COLUMN IF NOT EXISTS background text,
  ADD COLUMN IF NOT EXISTS alignment text,
  ADD COLUMN IF NOT EXISTS level integer DEFAULT 1,
  ADD COLUMN IF NOT EXISTS experience_points integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS str_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS dex_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS con_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS int_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS wis_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS cha_score integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS armor_class integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS initiative_override integer,
  ADD COLUMN IF NOT EXISTS speed integer DEFAULT 30,
  ADD COLUMN IF NOT EXISTS max_hp integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS current_hp integer DEFAULT 10,
  ADD COLUMN IF NOT EXISTS temp_hp integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hit_dice text,
  ADD COLUMN IF NOT EXISTS death_save_successes integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS death_save_failures integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS saving_throw_proficiencies text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS skill_proficiencies text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS skill_half_proficiencies text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS proficiencies_languages text,
  ADD COLUMN IF NOT EXISTS equipment jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS features_traits text,
  ADD COLUMN IF NOT EXISTS spell_slots jsonb DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS spellcasting_ability text,
  ADD COLUMN IF NOT EXISTS spells jsonb DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS personality_traits text,
  ADD COLUMN IF NOT EXISTS ideals text,
  ADD COLUMN IF NOT EXISTS bonds text,
  ADD COLUMN IF NOT EXISTS flaws text;
